# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvComments',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('html_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('official', models.NullBooleanField()),
                ('vote_sum', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at_timestamp', models.FloatField(blank=True, null=True)),
                ('created_at_str', models.CharField(blank=True, max_length=1024, null=True)),
                ('updated_at_timestamp', models.FloatField(blank=True, null=True)),
                ('updated_at_str', models.CharField(blank=True, max_length=1024, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isv_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvCommentsJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdoc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isv_comments_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvPosts',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('closed', models.NullBooleanField()),
                ('pinned', models.NullBooleanField()),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('featured', models.NullBooleanField()),
                ('html_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('topic_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('vote_sum', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at_timestamp', models.FloatField(blank=True, null=True)),
                ('created_at_str', models.CharField(blank=True, max_length=1024, null=True)),
                ('updated_at_timestamp', models.FloatField(blank=True, null=True)),
                ('updated_at_str', models.CharField(blank=True, max_length=1024, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isv_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvPostsJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdoc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isv_posts_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvTopics',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('html_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('position', models.CharField(blank=True, max_length=1024, null=True)),
                ('follower_count', models.CharField(blank=True, max_length=1024, null=True)),
                ('community_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.CharField(blank=True, max_length=1024, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_segment_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'isv_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsvUsers',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.CharField(blank=True, max_length=1024, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=1024, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=1024, null=True)),
                ('phone', models.CharField(blank=True, max_length=1024, null=True)),
                ('shared_phone_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('locale_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('locale', models.CharField(blank=True, max_length=1024, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('verified', models.NullBooleanField()),
                ('result_type', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'isv_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DBUpdateTime',
            fields=[
                ('timestamp', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'isv_update',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZendeskUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'zendesk_userinfo',
                'managed': True,
            },
        ),
    ]
